image: tiangolo/docker-with-compose

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build $CI_REGISTRY_IMAGE .
  tags:
    - docker

push:
  stage: push
  script:
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - docker
