image: tiangolo/docker-with-compose

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t kfbi/igctf .
  tags:
    - docker

push:
  stage: push
  script:
    - docker push kfbi/igctf
  tags:
    - docker
