version: "2"
services:
  bot:
    build: .
    image: kfbi/igctf
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - ./:/igctf
    depends_on:
      - mongo
    env_file:
      - bot-variables.env
  mongo:
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"

volumes:
  mongodb:
  mongodb_config: