version: "2"
services:
  bot:
    build: .
    image: ept/eptbot
    restart: always
    volumes:
      - ./bot:/eptbot
    depends_on:
      - mongo
    stop_signal: SIGKILL
  mongo:
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mdb:/data/db
      - mdb_config:/data/configdb

volumes:
  mdb:
    external: true
  mdb_config:
    external: true
